### PR TITLE
avoid onclick property in index.html

### PR DESCRIPTION
**Pull request by adbenitez**
avoid polluting window object, only add the debugging cheats, remove them from the UI only accessible via console

also make more explicit the loading of elements by id instead of using implicit hack

### CODE REVIEW

**Comment by r10s** [comment]
please revert the second prevStage/nextStage commit, with that, cheating becomes buggy to me (freezes, etc) - the old magic there seems to be needed somehow. also, not resetting the bunny position makes things easier, eg. you can go rightmost in level1, then cheat to level13 and are already done the first half and can become supper bunny (instead of super kitty)


otherwise lgtm

**Comment by adbenitez** [comment]
> please revert the second prevStage/nextStage commit, with that, cheating becomes buggy to me (freezes, etc)

for me it is the other way around, the prevStage doesn't work with the default code, it crashes,

and I changed it to do the same that is done on new level, so it should work the same as actually passing the level, I also noticed some freezing in the last level, I wonder if it is related to the cheat or a bug in the game :thinking:

**Comment by adbenitez** [comment]
(I reverted the change to the next/prev stage there seems to be bugs there but can be done in a more dedicated PR)

**Comment by r10s** [comment]
> or me it is the other way around, the prevStage doesn't work with the default code, it crashes

i never tried prevStage() - so maybe leave the changes there and leave nextStage() as is?

> I wonder if it is related to the cheat or a bug in the game 🤔

it does not happen when playing regulary, and iirc, also not with the old chating functions (was using that quite often)

**Review by r10s — APPROVED** [review]

**Pull request merged**
